// Matchmaking system with AI-generated problems
// Every duel gets a fresh unique problem generated by Claude!

import { supabase } from "./supabase"
import { generateProblem } from "./generateProblem"

export async function findOrCreateDuel(userId: string): Promise<{
  duelId: string
  problem: any
  isNewDuel: boolean
}> {
  console.log("🔍 Looking for waiting duels for user:", userId)

  // Check for waiting duels
  const { data: waitingDuels } = await supabase
    .from("duels")
    .select("*")
    .eq("status", "waiting")
    .neq("player1_id", userId)
    .limit(1)

  const waitingDuel = waitingDuels?.[0] || null

  if (waitingDuel) {
    console.log("✅ Joining existing duel:", waitingDuel.id)

    // Join the waiting duel as player 2
    const { data: updatedDuel } = await supabase
      .from("duels")
      .update({
        player2_id: userId,
        status: "active"
      })
      .eq("id", waitingDuel.id)
      .select()
      .single()

    // Get the problem that was already generated for this duel
    const { data: problem } = await supabase
      .from("problems")
      .select("*")
      .eq("id", updatedDuel!.problem_id)
      .single()

    return {
      duelId: updatedDuel!.id,
      problem,
      isNewDuel: false
    }
  }

  console.log("🤖 Generating AI problem...")

  // Pick a random difficulty
  const difficulties = ["EASY", "EASY", "MEDIUM", "MEDIUM", "HARD"]
  const difficulty = difficulties[
    Math.floor(Math.random() * difficulties.length)
  ] as "EASY" | "MEDIUM" | "HARD"

  // Generate a fresh problem with Claude AI
  const aiProblem = await generateProblem(difficulty)
  console.log("✨ AI Problem generated:", aiProblem.title)

  // Save the AI problem to our database
  const { data: savedProblem } = await supabase
    .from("problems")
    .insert({
      title: aiProblem.title,
      description: aiProblem.description,
      difficulty,
      examples: aiProblem.examples,
      constraints: aiProblem.constraints,
      test_cases: aiProblem.test_cases,
    })
    .select()
    .single()

  // Create the duel with the new problem
  const { data: newDuel } = await supabase
    .from("duels")
    .insert({
      player1_id: userId,
      problem_id: savedProblem!.id,
      status: "waiting"
    })
    .select()
    .single()

  console.log("🆕 New duel created:", newDuel!.id)

  return {
    duelId: newDuel!.id,
    problem: { ...savedProblem, ...aiProblem },
    isNewDuel: true
  }
}
